services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: task-manager-api:latest
    container_name: task-manager-api
    restart: always
    env_file:
      - .env
    environment:
      APP_PORT: ${APP_PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      PASSWORD_SECRET: ${PASSWORD_SECRET}
    ports:
      - "7000:7000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: task-manager-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      